config/routes.rb
Rails.application.routes.draw do
  # get 'comments/new'
  # post 'comments/create'
  
  get 'sessions/new'
  # get 'users/index'
  # get 'posts/index'
  
  root 'posts#posts_trend_day'
  
  get ':name/likes', to: 'users#likes' , as: 'user_likes'
  get ':name/comments', to: 'users#comments', as: 'user_comments'
  
  get 'posts/search',to: 'posts#search'
  
  get 'users/destroy_confirm',to: 'users#destroy_confirm'
  post 'users/destroy_confirm',to: 'users#destroy'
  
  get 'posts/daily', to: 'posts#posts_trend_day'
  get 'posts/weekly', to: 'posts#posts_trend_week'
  get 'posts/monthly', to: 'posts#posts_trend_month'
  get 'posts/all_ranks'
  
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :posts do
    resources :comments
  end
  
  resources :users,only:[:new,:create]
  # usernameにしたい
  resources :users, path: '/', only: [:show, :edit, :update, :destroy]
  
  
  post 'likes/:post_id/create',to: 'likes#create'
  post 'likes/:post_id/destroy',to: 'likes#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'about', to: 'home#about'
  
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  attr_accessor :remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  
  # usernameにしたい
  def to_param
    name
  end
  

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,12}+\z/i
  
  validates :name, presence: true,uniqueness: true
  
  validates :password, presence: true,format: { with: VALID_PASSWORD_REGEX },allow_nil: true
  
  has_many :posts
  has_many :comments
  
  has_secure_password
  

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:edit,:update,:destroy_confirm,:destroy]
  before_action :correct_user,   only:[:edit,:update]
  
  # def index
  #   @users = User.all.order(created_at: :desc)
  # end
  
  def show
    # usernameにしたい
    # @user = User.find_by(name: params[:id])
    # @user = User.find(params[:id])
    
    #アカウントが存在しなかったら、root_pathに飛ばす
    
    @user = User.find_by(name: params[:id])
    
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      # flash[:notice] = "ユーザーを作成いたしました"
      redirect_to root_path, success: '登録が完了しました。'
    else
      flash.now[:danger] = "登録に失敗しました。入力した値が正しいかご確認ください。"
      render :new
    end
  end

  def edit
    # @user = User.find(params[:id])
    @user = User.find_by(name: params[:id])
  end
  
  def update
    # @user = User.find_by(id: params[:id])
    # usernameにしたい
    @user = User.find_by(name: params[:id])
    if @user.update(user_params)
      # flash[:notice] = "ユーザーの編集が完了しました"
      redirect_to user_path,success: 'ユーザーの編集が完了しました'
    else
      flash.now[:danger] = "ユーザーの編集に失敗しました"
      render :edit
    end
  end
  
  def likes
    # @user = User.find(params[:id])
    @user = User.find_by(name: params[:name])
    @likes = Like.where(user_id: @user.id).order(updated_at: :desc)
  end
  
  def comments
    # @user = User.find(params[:id])
    @user = User.find_by(name: params[:name])
    @comments = Comment.where(user_id: @user.id).order(updated_at: :desc)
  end
  
  def destroy_confirm
    # たぶんこれいらない
    # @leave_reason = LeaveReason.new
  end
  
  def destroy
    @leave_reason = LeaveReason.create(content: params[:content])
    # @user = User.find(params[:id])
    @user = User.find(current_user.id)
    @user.destroy
    # flash[:notice] = 'ユーザーを削除しました'
    redirect_to root_path,info: 'ユーザー退会を完了いたしました。またのご利用をお待ちしております'
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email,:profile,:password,:password_confirmation,:image)
    end
    
    def logged_in_user
      unless logged_in?
      store_location
      # flash[:notice] = "ログインをしてください"
      redirect_to login_path
      flash[:danger]="ログインしてください"
      end
    end
    
    def correct_user
      # @user = User.find_by(id: params[:id])
      @user = User.find_by(name: params[:id])
      redirect_to root_path unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
      <%= render partial: "/users/user_image"%>
      
      <h2><%= @user.name %></h2>
      <br>
      【紹介文】
      <!--エスケープ処理でhttp,httpを許可している-->
      
      <hr>
        <% if @user.profile %>
          <p><%= sanitize text_url_to_link(@user.profile), tags: %w(b a), attributes: %w(href) %></p>
        <% end %>
      <hr>
      
      <ul class="user-menus">
  
        <li class="<%= 'user-header-selecting' if current_page?(user_path(@user)) %>"><%= link_to "投稿履歴",user_path(@user) %></li>
        
        <li class="<%= 'user-header-selecting' if current_page?(user_likes_path(@user)) %>"><%= link_to "いいね履歴",user_likes_path(@user) %></li>
        
        <li class="<%= 'user-header-selecting' if current_page?(user_comments_path(@user)) %>"><%= link_to "コメント履歴",user_comments_path(@user) %></li>
        
      </ul>

app/views/users/_user_image.html.erb
<!--あとで書き直す-->
<% if not @user %>
  <%= image_tag "default.jpg", :size => '100x100' %>
<% elsif @user.image? %>
  <%= image_tag @user.image.url %>
<% elsif not @user.image? %>
  <%= image_tag "default.jpg", :size => '100x100' %>
<% end %>

app/views/users/comments.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <%= render partial: "profile"%>
      
    <% @comments.each do |comment| %>
      <% post = Post.find(comment.post_id) %>

      
      <div class="posts-index-item">
        <div class="post-detail">
        
        <% if post.user%>
            <%= post.user.name%>
          <% else %>
            退会したユーザー
        <% end %>
        
        の投稿 <%= link_to post.title,post_path(post) %>にコメント
        <%= shape_create_time(comment.created_at) %>
        </div>
        <br>
        <%= comment.content%>
        
      </div>
    <% end %>
      

    </div>
  </div>
</div>

app/views/users/destroy_confirm.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ユーザーの退会</div>
    
コメント、投稿した履歴は残りますのでご了承ください。


<br>
<br>
<br>
<br>
<br>
<br>

退会理由についてお聞かせください。
  <%= form_with model: @leavereason,local: true do |f| %>
     <%= f.select :content, [["使わなくなった", "使わなくなった"], ["使いにくい", "使いにくい"], ["他にいいサイトがある", "他にいいサイトがある"], ["その他", "その他"]], include_blank: "選択して下さい" %>

     <%= f.submit '退会する',data: { confirm: '本当に退会してもよろしいですか?（一度退会したら元に戻せません）', cancel: 'キャンセル', commit: '退会する'}, title: '退会確認' %>
  <% end %>

        
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ユーザー情報の編集</div>
    <%= form_with model: @user, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form users-form">
        <br>
        <center>
        <% if @user.image? %>
          <%= image_tag @user.image.url %>
        <% else %>
          <%= image_tag "/assets/default.jpg", :size => '100x100' %>
        <% end %>
        
        <br>
        <br>
        <button type="button">
           <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
        </button>
        </center>
        
        <div class="form-body">
          <%= f.label :name, 'ユーザー名' %>
          <%= f.text_field :name %>
          
          <%= f.label :profile, 'プロフィール' %>
          <%= f.text_area :profile, placeholder: '紹介文を入力してください' %>
          
          
          
        　
          
          
          <%= f.submit "編集する"%>
        
        <%= link_to "退会を希望される方はこちら",users_destroy_confirm_path %>
        
        </div>
        
      </div>
    <% end %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <%= render partial: "profile"%>
      
      <% @likes.each do |like| %>
      
      <% post = Post.find_by(id: like.post_id) %>
      
      <div class="posts-index-item">
        
        <%= render 'layouts/post_detail', { post: post } %>
        
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    
    <%= form_with model: @user, local: true do |f| %>
    

    
    <%=  render 'layouts/error_messages', model: f.object %>
      <div class="form users-form">
        <div class="form-body">
          <%= f.label :name, 'ユーザー名' %>
          <%= f.text_field :name %>
          
          <%= f.label :email, 'メールアドレス' %>
          <%= f.text_field :email %>
          
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, placeholder: '8文字以上12文字以内(半角英数字それぞれ１文字以上含む)' %>
          
          <%= f.label :password_confirmation, 'パスワード(確認)' %>
          <%= f.password_field :password_confirmation %>
          
          
          <%= link_to 'ログインはこちら',login_path %>
          
          <%= f.submit "新規登録"%>
        </div>
      </div>
    <% end %>
    
    
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <%= render partial: "profile", locals: { user: @user } %>
      
      <% @posts = @user.posts.all.order(updated_at: :desc) %>
      <% @posts.each do |post| %>
      
        <div class="posts-index-item">
          
          <%= link_to post.title,post_path(post)%>
          
          <div class="post-detail">

            投稿日時 <%= shape_create_time(post.created_at) %>
            <i class="material-icons">
              favorite
            </i>
            <%= Like.where(post_id: post.id).count %>
          </div>
          
          
        </div>
      <% end %>

    </div>
  </div>
</div>