config/routes.rb
Rails.application.routes.draw do
  # get 'comments/new'
  # post 'comments/create'
  
  get 'sessions/new'
  # get 'users/index'
  # get 'posts/index'
  
  root 'posts#posts_trend_day'
  
  get ':name/likes', to: 'users#likes' , as: 'user_likes'
  get ':name/comments', to: 'users#comments', as: 'user_comments'
  
  get 'posts/search',to: 'posts#search'
  
  get 'users/destroy_confirm',to: 'users#destroy_confirm'
  post 'users/destroy_confirm',to: 'users#destroy'
  
  get 'posts/daily', to: 'posts#posts_trend_day'
  get 'posts/weekly', to: 'posts#posts_trend_week'
  get 'posts/monthly', to: 'posts#posts_trend_month'
  get 'posts/all_ranks'
  
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :posts do
    resources :comments
  end
  
  resources :users,only:[:new,:create]
  # usernameにしたい
  resources :users, path: '/', only: [:show, :edit, :update, :destroy]
  
  
  post 'likes/:post_id/create',to: 'likes#create'
  post 'likes/:post_id/destroy',to: 'likes#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'about', to: 'home#about'
  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="header-logo">
    <%= link_to "TSUKUTTE", root_path %>
  </div>
  
<ul class="header-menus">
  
  
  <% if logged_in? %>
  
    
    <li>
      <%= form_with(url: posts_search_path, method: :get, local: true) do |f| %>
        <%= f.text_field :search, placeholder:"\uF002 キーワードを入力",id:"sbox1",class:'fa' %>
        
        
      <% end %>

      
    </li>
    

      
      
      <!--<div id="wrap">-->
      <!--  <form action="" autocomplete="on">-->
      <!--  <input id="search" name="search" type="text" placeholder="検索！">
            <input id="search_submit" value="Rechercher" type="submit">-->
      <!--  </form>-->
      <!--</div>-->
      
    
    <li>
      <%= link_to "新規投稿", new_post_path %>
    </li>
    
    <li class="nav-item dropdown">
          
          <!--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <!--    <i class="material-icons">-->
          <!--      reorder-->
          <!--    </i>-->
          <!--</a>-->

          <%= link_to "#" ,class: "nav-link dropdown-toggle" ,id:"navbarDropdownMenuLink",  role: "button",'data-toggle': :dropdown, "aria-haspopup": "true","aria-expanded": "false" do %>　　
            <i class="material-icons">reorder</i>
          <% end %>
          
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "マイページ", user_path(current_user) ,class:"dropdown-item"%>
            <%= link_to "編集", edit_user_path(current_user),class: "dropdown-item"%>
            <%= link_to 'ログアウト', logout_path,method: :delete , data: { confirm: 'ログアウトしてよろしいですか？', cancel: 'キャンセル', commit: 'ログアウトする'}, title: 'ログアウト確認' ,class: "dropdown-item" %>
          </div>
          
    </li>            

  <% else %>
    
    <li>
      <%= form_with(url: posts_search_path, method: :get, local: true) do |f| %>
        <%= f.text_field :search, placeholder:"\uF002 キーワードを入力",id:"sbox1",class:'fa' %>
        
        
      <% end %>

      
    </li>
    
    <li>
      <%= link_to "新規登録", new_user_path %>
    </li>
    
    <li>
      <%= link_to 'ログイン', login_path %>
    </li>
    
  <% end %>
</ul>
</header>

app/views/layouts/_post_detail.html.erb
<!--投稿詳細のテンプレート（名前、投稿日時、ハートマーク）-->
  <%= link_to post.title,post_path(post)%>
  
  <div class="post-detail">
  
    <% if post.user%>
    by <%=  link_to "#{post.user.name}",user_path(post.user), class: "post-detail" %>
    <% else %>
      退会したユーザー
    <% end %>
    
    
    投稿日時 <%= shape_create_time(post.created_at) %>
    <i class="material-icons">
      favorite
    </i>
    <%= Like.where(post_id: post.id).count %>
  </div>

app/views/layouts/_top_container.html.erb
<div class="top-container">
    <ul>
    	<li class="<%= 'index-header-selecting' if current_page?(root_path) or current_page?(posts_weekly_path) or current_page?(posts_monthly_path) %>">
    	  <%= link_to  root_path do %>
          <i class="material-icons">trending_up</i> トレンド
        <% end %>
    	</li>

    	
    	
    	<li class="<%= 'index-header-selecting' if current_page?(posts_path) %>">
    	  <%= link_to  posts_path do %>
              <i class="material-icons">fiber_new</i> 最新の投稿
          <% end %>
    	</li>
    	
    	<li class="<%= 'index-header-selecting' if current_page?(posts_all_ranks_path) %>">
    	  <%= link_to  posts_all_ranks_path do %>
          <i class="material-icons">import_export</i> 過去のいいねランク
        <% end %>
    	</li>
    	

    </ul>
</div>

app/views/layouts/_trend_header.html.erb
<i class="material-icons">
     trending_up
</i>
トレンド
    
    
<!--if文で色が変わるように条件分岐-->
<ul class="index-header-menus">
  
    <li class="<%= 'index-header-selecting' if current_page?(root_path) %>"><%= link_to '１日', root_path %></li>

    <li class="<%= 'index-header-selecting' if current_page?(posts_weekly_path) %>"><%= link_to '週間', posts_weekly_path %></li>
    
    <li class="<%= 'index-header-selecting' if current_page?(posts_monthly_path) %>"><%= link_to '月間', posts_monthly_path %></li>
    
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TSUKUTTE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">-->
  </head>

  <body>
    
    <%= render 'layouts/header'%>
    
    
    
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(3000);
      });
    </script>
  </body>
</html>